set nocompatible

"source $VIMRUNTIME/mswin.vim
"behave mswin

set fileencodings=utf-8,gbk,default,latin1
set encoding=utf-8  
set termencoding=utf-8  
set fileencoding=utf-8  
set imcmdline    
" use chinese help
set helplang=cn
syntax enable

" vim-powerline
set laststatus=2
set t_Co=256
let g:Powerline_symbols='unicode'
"set encoding=utf8

let g:winManagerWindowLayout='FileExplorer|TagList'
nmap wm :WMToggle<cr>

filetype off

set rtp+=$VIM/vimfiles/bundle/Vundle.vim/
let path='$VIM/vimfiles/bundle'
"set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin(path)

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'

" plugin from http://vim-scripts.org/vim/scripts.html
Plugin 'L9'
Bundle 'The-NERD-tree'
Bundle 'winmanager'
" install ctags http://sourceforge.net/projects/ctags/files/
Bundle 'taglist.vim'
Bundle 'minibufexpl.vim'
Bundle 'bufexplorer.zip'

Bundle 'https://github.com/Lokaltog/vim-powerline.git'

" Git plugin not hosted on GitHub
Plugin 'git://git.wincent.com/command-t.git'

Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}

call vundle#end()            " required
filetype plugin indent on    " required

