#! /bin/sh
### BEGIN INIT INFO
# Provides:          Nginx-php-fpm(fastcgi)
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     3 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop nginx-fcgi in external FASTCGI mode
# Description:       Start and stop nginx-fcgi in external FASTCGI mode
# http://www.linxutone.org msn:cnseek@msn.com
### END INIT INFO 

NGINX="/usr/local/nginx/sbin/nginx"
PIDFILE="/var/log/nginx.pid"
#PIDLIST="pgrep nginx|xargs kill -9"
PHPCGI="/usr/local/php-fcgi/sbin/php-fpm"

# Source function library.
. /etc/init.d/functions

if [ ! -f /etc/sysconfig/network ]; then
    exit 0
fi
 
[ -x "$NGINX" ] || exit 0
 
do_start()
{
    if [ -f $PIDFILE ]; then
        echo "Nginx program is runing!!!"
        exit 1
    else
        ulimit -SHn 51200
        $PHPCGI start
        $NGINX
        echo "Nginx program is the successful start!!! "
    fi
 
}
 
do_stop()
{
    if  [ -f $PIDFILE ]; then
        $PHPCGI stop
        kill -QUIT `cat $PIDFILE`
        rm -f $PIDFILE
        PIDLIST="pgrep nginx|xargs kill -9 2>/dev/null;"
        eval $PIDLIST
        echo "Nginx program is stoping"
    else
        echo "Nginx program is not runing!!!"
    fi
}
 
do_reload ()
{
    if [ -f $PIDFILE ]; then
        kill -HUP `cat $PIDFILE`
        echo "Nginx program is reload"
    else
        echo "Nginx program is not runing!!!"
    fi
}
 
case "$1" in
    start)
        do_start
    ;;
    stop)
        do_stop
    ;;
    restart)
        do_stop
        do_start
    ;;
    reload)
        do_reload
    ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload}"
    ;;
esac
